version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: github.com/lib/pq
    versions:
    - 1.10.0
    - 1.9.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.0
    - 1.7.1
    - 1.8.0
- package-ecosystem: npm
  directory: "/web-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - Alex-CS
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: google-protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: svelte-loader
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
  - dependency-name: polka
    versions:
    - 1.0.0-next.11
    - 1.0.0-next.13
  - dependency-name: eslint-plugin-svelte3
    versions:
    - 3.0.0
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: purgecss-webpack-plugin
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: purgecss
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: sapper
    versions:
    - 0.29.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: golang
    versions:
    - 1.15.7
    - 1.15.8
    - 1.16.0
    - 1.16.1
    - 1.16.2
- package-ecosystem: docker
  directory: "/web-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: node
    versions:
    - ">= 13.a, < 14"
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
- package-ecosystem: docker
  directory: "/envoy"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/nginx"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
