output:
  show-stats: true
linters-settings:
  gci:
    sections:
      - standard
      - default
      - blank
      - prefix(github.com/pubgolf/pubgolf)
  wsl:
    # allow-assign-and-anything: true
    allow-cuddle-declarations: true
    force-err-cuddling: true
  exhaustive:
    check:
      - switch
      - map
linters:
  enable-all: true
  disable:
    # No plans to enable (mostly complexity measures or extremely dogmatic).
    - cyclop
    - depguard
    - dogsled
    - dupl
    - execinquery
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godox
    - gomnd
    - lll
    - maintidx
    - mnd
    - prealloc
    - rowserrcheck
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - unused
    - varnamelen

    # Deprecated checks: deactivating to suppress warning.
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
