version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    image: "escavelo/pubgolf-api${DOCKER_LABEL}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - proxy_pass
      - data_access
    env_file:
      - .env
  web-app:
    build:
      context: ./
      dockerfile: ./web-app/Dockerfile
    image: "escavelo/pubgolf-web-app${DOCKER_LABEL}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    networks:
      - proxy_pass
    environment:
      PORT: "${WEBAPP_PORT}"
    env_file:
      - .env
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image:  "escavelo/pubgolf-envoy${DOCKER_LABEL}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${ENVOY_ADMIN_PORT}:${ENVOY_ADMIN_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
    networks:
      - proxy_pass
    environment:
      ADMIN_PORT: "${ENVOY_ADMIN_PORT}"
      GRPC_WEB_INBOUND_PORT: "${GRPC_WEB_PORT}"
      API_UPSTREAM_HOST: "${API_HOST}"
      API_UPSTREAM_PORT: "${API_PORT}"
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    image: "escavelo/pubgolf-nginx${DOCKER_LABEL}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_pass
    volumes:
      - ./certs:/etc/cloudflare/certs
      - ./data/certbot/conf:/etc/letsencrypt
    env_file:
      - .env
  db:
    image: postgres
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${HOST_DB_PORT}:5432"
    networks:
      - data_access
    volumes:
      - "${HOST_DB_DATA_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_NAME: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  testdb:
    image: postgres
    ports:
      - "${HOST_TEST_DB_PORT}:5432"
    networks:
      - data_access
    environment:
      POSTGRES_NAME: pubgolf_test
      POSTGRES_USER: pubgolf_test
      POSTGRES_PASSWORD: pubgolf_test
networks:
  proxy_pass:
  data_access:
