version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - proxy_pass
      - data_access
    env_file:
      - .env
  web-app:
    build:
      context: ./
      dockerfile: ./web-app/Dockerfile
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    networks:
      - proxy_pass
    environment:
      PORT: "${WEB_APP_PORT}"
    env_file:
      - .env
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${ENVOY_ADMIN_PORT}:${ENVOY_ADMIN_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
    networks:
      - proxy_pass
    env_file:
      - .env
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_pass
    volumes:
      - ./certs:/etc/cloudflare/certs
      - ./data/certbot/conf:/etc/letsencrypt
    env_file:
      - .env
  db:
    image: postgres
    restart: "${RESTART_POLICY:-unless-stopped}"
    ports:
      - "${HOST_DB_PORT}:5432"
    networks:
      - data_access
    volumes:
      - "${HOST_DB_DATA_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_NAME: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  testdb:
    image: postgres
    ports:
      - "${HOST_TEST_DB_PORT}:5432"
    networks:
      - data_access
    environment:
      POSTGRES_NAME: "${TEST_DB_NAME}"
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASSWORD}"
networks:
  proxy_pass:
  data_access:
