name: "CI/CD Workflow"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  proto_build_and_check:
    name: Build and Check Protos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Buf CLI
        uses: bufbuild/buf-setup-action@v1
      - name: Lint .proto Files
        uses: bufbuild/buf-lint-action@v1
      - name: Check Breaking Changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=develop"
      - name: Generate Protos
        run: |
          buf generate --template buf.gen.ci.yaml
          zip -r build/proto.zip build/proto/
      - name: Upload Generated Protos as CI Artifact
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/develop'
        with:
          name: generated-protos
          path: build/proto.zip

  publish_gh_release:
    name: Publish Client Deps and Tools
    needs: proto_build_and_check
    runs-on: ubuntu-latest
    steps:
      - name: Download CI Artifact
        uses: actions/download-artifact@v3
        with:
          name: generated-protos
      - name: Upload as GitHub Release
        if: github.ref == 'refs/heads/develop'
        uses: softprops/action-gh-release@v1
        with:
          files: proto.zip
          tag_name: sha-${{ github.sha }}
