name: Deploy to Staging

on:
  push:
    branches:
      - develop
      - '**--stage'
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Images and Update Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose build web-app
        docker-compose down
        docker-compose up -d --force-recreate
