name: Deploy to Prod

on:
  push:
    branches:   
      - master  
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish API to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: escavelo/pubgolf-api:master
        username: thedeerchild
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./api/Dockerfile
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
    - name: Publish Web App to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: escavelo/pubgolf-web-app:master
        username: thedeerchild
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./api/Dockerfile
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
    - name: Publish Envoy to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: escavelo/pubgolf-envoy:master
        username: thedeerchild
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./envoy/Dockerfile
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
    - name: Publish Nginx to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: escavelo/pubgolf-nginx:master
        username: thedeerchild
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./nginx/Dockerfile
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
    - name: Copy files via SCP and Update Docker Compose
      uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.SSH_KEY_PROD }}
        host: pubgolf.co
        user: deployer
        scp: |
          docker-compose.yml deployer@pubgolf.co:~/pubgolf/
          bin/* deployer@pubgolf.co:~/pubgolf/bin/
          api/db/migrations/* deployer@pubgolf.co:~/pubgolf/db/migrations/
          api/db/seeds/prod-* deployer@pubgolf.co:~/pubgolf/db/seeds/
        ssh_after: |
          cd /home/deployer/pubgolf
          sudo docker-compose pull
          sudo docker-compose up -d
