name: "Build and Release Protobufs"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=develop"
      - name: Generate Protos
        run: |
          buf generate --template buf.gen.ci.yaml
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/develop'
        with:
          name: generated-protos
          path: build/proto/
  publish:
    needs: build_and_check
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-protos
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/proto/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
