name: "Build and Release Protobufs"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Buf CLI
        uses: bufbuild/buf-setup-action@v1
      - name: Lint .proto Files
        uses: bufbuild/buf-lint-action@v1
      - name: Check Breaking Changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=develop"
      - name: Generate Protos
        run: |
          buf generate --template buf.gen.ci.yaml
      - name: Upload Generated Protos as CI Artifact
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/develop'
        with:
          name: generated-protos
          path: build/proto/
  publish:
    needs: build_and_check
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Download CI Artifact
        uses: actions/download-artifact@v3
        with:
          name: generated-protos
      - name: Debug
        run: |
          ls ${{github.workspace}}/build/proto
          ls ${{github.workspace}}/build/proto/go
          ls ${{github.workspace}}/build/proto/swift
      - name: Upload as GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/build/proto/**/*
          tag_name: sha-${{ github.sha }}
