name: proto
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-lint-action@v1
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=develop'
      - name: Check all generated code is vendored for latest proto spec
        run: |
          buf generate
          git diff-index --quiet HEAD
