name: "Build And Check Protobufs"
on: pull_request
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
        with:
          version: '1.0.0-rc8'
      - uses: bufbuild/buf-lint-action@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.19.1'
      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@$GO_VERSION
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@$GO_GRPC_VERSION
          npm install -g ts-proto@$TS_PROTO_VERSION
        env:
          GO_VERSION: 'v1.26.0'
          GO_GRPC_VERSION: 'v1.1'
          TS_PROTO_VERSION: '^1.95.0'
      - name: Check all generated code is vendored for latest proto spec
        run: |
          buf generate
          # Call diff to force the mtime changes to be resolved, otherwise diff-index will give us a false positive.
          git diff > /dev/null
          git diff-index --quiet HEAD -- || ( git status -vv && exit 1 )
      - name: Check client versions are updated if there are proto changes
        run: |
          if bin/check-file-edited $GITHUB_BASE_REF $GITHUB_HEAD_REF 'proto/api/.*' ; then 
            bin/check-file-edited $GITHUB_BASE_REF $GITHUB_HEAD_REF 'proto/versions/current/go/version.go' &&
            bin/check-file-edited $GITHUB_BASE_REF $GITHUB_HEAD_REF 'proto/versions/current/ts/version.ts' &&
            bin/check-file-edited $GITHUB_BASE_REF $GITHUB_HEAD_REF 'proto/versions/current/objc/version.h';
          fi
      - name: Check server version is updated if there are breaking proto changes
        run: |
          if ! buf breaking --against '.git#branch=develop' ; then 
            bin/check-file-edited $GITHUB_BASE_REF $GITHUB_HEAD_REF 'proto/versions/mincompatible/go/version.go';
          fi
