name: "Build And Check Protobufs"
on: pull_request
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-lint-action@v1
      - name: Install protoc plugins
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          npm install -g ts-proto
      - name: Check all generated code is vendored for latest proto spec
        run: |
          buf generate
          git diff-index --quiet HEAD
      - name: Check all generated code is vendored for latest proto spec
        run: |
          buf generate
          git diff --name-only ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF}
